alloy-logs:
  alloy:
    clustering:
      enabled: true
    mounts:
      varlog: false
  enabled: true
alloy-singleton:
  enabled: true
cluster:
  name: multiverse
clusterEvents:
  enabled: true
destinations:
- name: loki
  type: loki
  url: http://loki-gateway.monitoring.svc:80/loki/api/v1/push
podLogsViaKubernetesApi:
  enabled: true
