tunnel: multiverse
credentials-file: /etc/cloudflared/multiverse.json

ingress:
  - hostname: home.chelseablue.cloud
    service: http://192.168.1.240:80

  - hostname: grafana.chelseablue.cloud
    service: http://192.168.1.240:80

  - hostname: jenkins.chelseablue.cloud
    service: http://127.0.0.1:8080

  - service: http_status:404
